spring:
  application:
    name: "health-service"
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.ful6wu7.mongodb.net/health-database?retryWrites=true&w=majority

server:
  port: 0


